### ISSUE TITLE
Querying VPC Details

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud-docs/virtual-private-cloud#23]
How can i query secondary cidr blocks?

**Comment by lhajba** [comment]
hi @generalpax There is no secondary cidr block for the VPC, but if you are referring to query of the subnet you can check under the API documentation \ APIs \ Subnet \ Querying Subnet. If you don't know the Subnet ID you can use the VPC ID as a filtering condition to query the related subnet(s) to your VPC (APIs \ Subnet \ Querying Subnets).

**Comment by generalpax** [comment]
Yes there is. In API v3: https://support.huaweicloud.com/intl/en-us/usermanual-vpc/vpc_vpc_0007.html
Unfortunately v3 in our case in eu-ch2 region is just implemented on the console api.

**Comment by lhajba** [comment]
We don't have this feature at OTC not even in EU-CH2 region .
