### ISSUE TITLE
Binding a Virtual IP Address to an EIP or ECS

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/virtual-private-cloud#24]
Issue on page:        https://github.com/opentelekomcloud-docs/virtual-private-cloud/blob/main/umn/source/operation_guide_new_console_edition/virtual_ip_address/binding_a_virtual_ip_address_to_an_eip_or_ecs.rst

As there is a separate tutorial for binding a VIP to an EIP, the title "Binding a Virtual IP Address to an ECS" would make much more sense.

**Comment by lhajba** [comment]
Thanks for raising! It's a different process, but same result if you want to bind the Virtual IP Address to an EIP. "Binding a Virtual IP Address to an EIP" covers it from VPC/EIP part of console, while "Binding a Virtual IP Address to an EIP or ECS" covers it from VPC/Subnet. I think those steps should be separated from each other and this way the renaming can happen. It will be handled in an upcoming version later.

**Comment by lhajba** [comment]
VPC UMN update was released with fixing the issue.
